




hs.configdir ~/.hammerspoon/ path  


--
--
-- local allText = [[
-- 0. key = SC8ESK8HM2XP day = 30 cellphoneID = 0 end_day = 0
-- 1. key = 7ZDE3BJ3DGIB day = 365 cellphoneID = 0 end_day = 0
-- 2. key = 6M7328PPMNP8 day = 365 cellphoneID = 0 end_day = 0
-- 3. key = JQC38QV4W7PN day = 365 cellphoneID = 0 end_day = 0
-- 4. key = ESNHK5TE9CFG day = 365 cellphoneID = 0 end_day = 0
-- 5. key = IDY4XIPBK8C2 day = 365 cellphoneID = 0 end_day = 0
-- 6. key = FICWE7CDQBGG day = 365 cellphoneID = 0 end_day = 0
-- 7. key = 7IYKZT9J9S25 day = 365 cellphoneID = 0 end_day = 0
-- 8. key = 2J84VSGS3PU8 day = 365 cellphoneID = 0 end_day = 0
-- 9. key = D3CN4695K3RX day = 365 cellphoneID = 0 end_day = 0
-- 10. key = 5IDFUYWDNYBV day = 365 cellphoneID = 0 end_day = 0
-- 11. key = 27ARS7MD8PYF day = 365 cellphoneID = 0 end_day = 0
-- 12. key = 2DE6UC8V92CU day = 365 cellphoneID = 0 end_day = 0
-- 13. key = 2ERSY6Q5GKTM day = 365 cellphoneID = 0 end_day = 0
-- 14. key = AJCPP6V9DU6B day = 365 cellphoneID = 0 end_day = 0
-- 15. key = J7NRP6BEP3R9 day = 365 cellphoneID = 0 end_day = 0
-- 16. key = BVNIBKPNHARC day = 365 cellphoneID = 0 end_day = 0
-- 17. key = XTZ5MX7USX7D day = 365 cellphoneID = 0 end_day = 0
-- 18. key = 8BZTFWV6MH5R day = 365 cellphoneID = 0 end_day = 0
-- 19. key = 9HY4TRVZUFDK day = 365 cellphoneID = 0 end_day = 0
-- 20. key = PDIRDBIQP5BN day = 365 cellphoneID = 0 end_day = 0
-- 21. key = UP5DNZQ2Y6JH day = 365 cellphoneID = 0 end_day = 0
-- 22. key = S8IEMDIW7NMJ day = 365 cellphoneID = 0 end_day = 0
-- 23. key = UEXNK63DERHH day = 365 cellphoneID = 0 end_day = 0
-- 24. key = CUJZIKIH6EDJ day = 365 cellphoneID = 0 end_day = 0
-- 25. key = H84ZZHIDDBM5 day = 365 cellphoneID = 0 end_day = 0
-- 26. key = RCWDUKAAHAGI day = 365 cellphoneID = 0 end_day = 0
-- 27. key = YPTN4BBITQTC day = 365 cellphoneID = 0 end_day = 0
-- 28. key = YYIMHWK5T4YK day = 365 cellphoneID = 0 end_day = 0
-- 29. key = KCC448TGWGEY day = 365 cellphoneID = 0 end_day = 0
-- 30. key = V8TMC5GGXSWF day = 365 cellphoneID = 0 end_day = 0
-- 31. key = V56Z8YUC88A4 day = 365 cellphoneID = 0 end_day = 0
-- 32. key = 5KNX3ACB7QHM day = 365 cellphoneID = 0 end_day = 0
-- 33. key = VHWNYMTGT4G6 day = 365 cellphoneID = 0 end_day = 0
-- 34. key = 5URSR3P466B7 day = 365 cellphoneID = 0 end_day = 0
-- 35. key = S7MCP3N5P58C day = 365 cellphoneID = 0 end_day = 0
-- 36. key = 9ZYRVIUN5RVT day = 365 cellphoneID = 0 end_day = 0
-- 37. key = JSD8KDVW7226 day = 365 cellphoneID = 0 end_day = 0
-- 38. key = PV2AP2JN5NCK day = 365 cellphoneID = 0 end_day = 0
-- 39. key = 9SYBFFI38TSH day = 365 cellphoneID = 0 end_day = 0
-- 40. key = M8KD5W34US5T day = 365 cellphoneID = 0 end_day = 0
-- 41. key = 8YPIWUGKC4BW day = 365 cellphoneID = 0 end_day = 0
-- 42. key = WVMZ4SH53ZMD day = 365 cellphoneID = 0 end_day = 0
-- 43. key = 428KI5UKHAQN day = 365 cellphoneID = 0 end_day = 0
-- 44. key = 9EWUHG7GDZWY day = 365 cellphoneID = 0 end_day = 0
-- 45. key = SW5B8MWVXVI7 day = 365 cellphoneID = 0 end_day = 0
-- 46. key = 5WXJ8C8QPVD3 day = 365 cellphoneID = 0 end_day = 0
-- 47. key = P7CUUNP5YUMI day = 365 cellphoneID = 0 end_day = 0
-- 48. key = CFBICTXXYAG7 day = 365 cellphoneID = 0 end_day = 0
-- 49. key = PKCC5968GSU7 day = 365 cellphoneID = 0 end_day = 0
-- 50. key = ZQIIFDSHBX36 day = 365 cellphoneID = 0 end_day = 0
-- 51. key = 589YSWZTPRNV day = 365 cellphoneID = 0 end_day = 0
-- 52. key = UQRND7J8F2YB day = 365 cellphoneID = 0 end_day = 0
-- 53. key = S5Y9SV54TXMQ day = 365 cellphoneID = 0 end_day = 0
-- 54. key = Y6GSB8URREC5 day = 365 cellphoneID = 0 end_day = 0
-- 55. key = TY4JSSXH3UMI day = 365 cellphoneID = 0 end_day = 0
-- 56. key = WYNCMKCR82TG day = 365 cellphoneID = 0 end_day = 0
-- 57. key = 9PKVVJNSV42T day = 365 cellphoneID = 0 end_day = 0
-- 58. key = XSNCD2HATPAB day = 365 cellphoneID = 0 end_day = 0
-- 59. key = 559WIHX5CF4J day = 365 cellphoneID = 0 end_day = 0
-- 60. key = XCSPVUNAAHB2 day = 30 cellphoneID = 0 end_day = 0
-- 61. key = BJCVN7EIGPIA day = 30 cellphoneID = 0 end_day = 0
-- 62. key = 8QP5TEA8GK6M day = 32 cellphoneID = 0 end_day = 0
-- ]]
--
-- local tab = removeSameStringInArray( arrayWithStringAndSplit(allText, " "))
--
-- for i,v in ipairs(tab) do
--     if #v==12 then
--         print(v)
--         os.execute("curl \"http://119.28.203.18/index.php?action=setup&user=joyspaces&password=joys100100100&delete="..v.."\"")
--     end
-- end



-- --
-- -- local co = coroutine.create(function()
-- --     for i=1,10 do
-- --         print("co", i)
-- --         coroutine.yield()
-- --     end
-- -- end)
-- --
-- -- print(coroutine.status(co))
-- --
-- -- coroutine.resume(co)
-- --
-- -- print(coroutine.status(co))
-- --
-- --
-- function findLongestString(str, sep)
--     local n = -1
--     for w in string.gmatch(str, sep) do
--         n = math.max(n, #w-1)
--     end
--     return n
-- end
--
-- function serialize(o)
--     if type(o) == "number" then
--         io.write(o)
--     elseif type(o) == "string" then
--         io.write(string.format("%q",o))
--     elseif type(o) == "table" then
--         io.write("{\n")
--         for k,v in pairs(o) do
--             io.write("  ",k," = ")
--             serialize(o)
--             io.write(",\n")
--         end
--         io.write("}\n")
--     else
--         error("cannot serialize a" .. type(o))
--     end
-- end
-- function readOnly(t)
--     local proxy = {}
--     local mt = {
--         __index = t,
--         __newindex = function(t,k,v)
--             error("attempt to update a read-only table", 2)
--         end
--     }
--     setmetatable(proxy, mt)
--     return prixy
-- end
-- -- 排序
-- function pairsByKeys(t, f)
--     local a = {}
--     for k,v in pairs(table_name) do
--         a[#a+1] = v
--     end
--     table.sort(a, f)
--     local i = 0
--     return function()
--         i = i + 1
--         return a[1], t[a[i]]
--     end
-- end
-- function rconcat(t)
--     if (type(t) ~= "table") then return t end
--     local res = {}
--     for i=1, #t do
--         res[i] = rconcat(t[i])
--     end
--     return table.concat(res)
-- end
-- function escape(s)
--     s = string.gsub(s, "[&=+%%%c]", function(h) return string.format("%%%02x",string.byte(c)) end)
--     s = string.gsub(s, " ", "+")
--     return s;
-- end
-- function unescape(s)
--     s = string.gsub(s, "+", " ")
--     s = string.gsub(s, "%%(%x%x)", function(h) return string.char(tonumber(h, 16)) end)
--     return s;
-- end
-- os.getenv("HOME") -- path
--
-- --
-- function qsDebug(func)
--     local tab = debug.getinfo(func)
--     for k,v in pairs(tab) do
--         print( "key = ", k , " var = ", v)
--     end
-- end
